---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: torpedo-controller
  namespace: metacontroller
spec:
  replicas: 1
  selector:
    matchLabels:
      torpedo-controller: enabled
  template:
    metadata:
      labels:
        torpedo-controller: enabled
    spec:
      nodeSelector:
        torpedo-controller: enabled
      containers:
      - name: controller
        image: hemanth43/python_pyyaml_jinja2:3.5
        ports:
        - containerPort: 30025
        command: ["python3", "/hooks/sync.py"]
        volumeMounts:
        - name: hooks
          mountPath: /hooks/templates
        - name: torpedo-metacontroller
          mountPath: /hooks
          subPath: sync.yaml
          
      volumes:
      - name: hooks
        configMap:
          name: torpedo-controller
          items:
            - key: torpedo-chaos-job.yaml
              path: torpedo-chaos.yaml
            - key: sanity_checks.yaml
              path: sanity_checks.yaml
            - key: torpedo_argo.j2
              path: torpedo_argo.j2
            - key: traffic-parameters.yaml
              path: traffic-parameters.yaml
            - key: chaos-parameters.yaml
              path: chaos-parameters.yaml
            - key: torpedo-traffic-orchestrator.yaml
              path: torpedo-traffic-orchestrator.yaml
---
apiVersion: v1
kind: Service
metadata:
  name: torpedo-controller
  namespace: metacontroller
  labels:
    torpedo-controller: enabled
spec:
  selector:
    torpedo-controller: enabled
  type: NodePort
  ports:
    - port: 30025
      nodePort: 30025
